s = "hello world"
# print("capitalize:", s.capitalize())
# print("casefold:", s.casefold())
# print("center:", s.center(20))
# print("count:", s.count("l"))
# print("encode:", s.encode())
# print("endswith:", s.endswith("world"))
# print("expandtabs:", "a\tb".expandtabs(5))
# print("find:", s.find("o"))
# print("format:", "My name is {}".format("Kaaveri"))
# print("format_map:", "{name}".format_map({"name": "Kaaveri"}))
# print("index:", s.index("e"))
# print("isalnum:", "abc123".isalnum())
# print("isalpha:", "hello".isalpha())
# print("isascii:", "abc123".isascii())
# print("isdecimal:", "123".isdecimal())
# print("isdigit:", "123".isdigit())
# print("isidentifier:", "my_var".isidentifier())
# print("islower:", "hello".islower())
# print("isnumeric:", "1234".isnumeric())
# print("isprintable:", "hello!".isprintable())
# print("isspace:", "   ".isspace())
# print("istitle:", "Hello World".istitle())
# print("isupper:", "HELLO".isupper())
# print("join:", "-".join(["a", "b", "c"]))
# print("ljust:", "hi".ljust(10))
# print("lower:", "HELLO".lower())
# print("lstrip:", "   hello".lstrip())

# maketrans & translate
table = str.maketrans("ae", "12")
print("translate:", "peace".translate(table))

print("partition:", "hello-world-python".partition("-"))
print("replace:", "hello world".replace("world", "Python"))
print("rfind:", "banana".rfind("a"))
print("rindex:", "banana".rindex("a"))
print("rjust:", "hi".rjust(10))
print("rpartition:", "hello-world-python".rpartition("-"))
print("rsplit:", "a,b,c".rsplit(","))
print("rstrip:", "hello    ".rstrip())
print("split:", "a b c".split())
print("splitlines:", "hello\nworld".splitlines())
print("startswith:", "python".startswith("py"))
print("strip:", "   hello   ".strip())
print("swapcase:", "HeLLo".swapcase())
print("title:", "hello world".title())
print("upper:", "hello".upper())
print("zfill:", "42".zfill(5))
